TM.Names = [
	"Kildare Street",
	"Leeson Street",
	"Marlborough Street",
	"Marrowbone Lane",
	"Merrion Road",
	"Merrion Square",
	"Merrion Street",
	"Molesworth Street",
	"Mountjoy Square",
	"Naas Road",
	"Nassau Street",
	"Newbridge Avenue",
	"North Circular Road",
	"North Strand Road",
	"Nutley Lane",
	"O'Connell Street",
	"Park Avenue",
	"Parliament Street",
	"Parnell Square",
	"Parnell Street",
	"Pearse Street",
	"Pembroke Road",
	"Raglan Road",
	"St John's Road East (St John's Road)",
	"St Stephen's Green",
	"Sandymount Avenue",
	"Serpentine Avenue",
	"South Circular Road",
	"Stillorgan Road",
	"Sydney Parade Avenue",
	"Talbot Street",
	"Temple Bar",
	"Templeogue Road",
]

